# Generated by Django 5.2.6 on 2025-09-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='logsheet',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='logsheet',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='route',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='is_deleted',
        ),
    ]
